### ISSUE TITLE
is there any code about Cross-Attention RNN or other models?

### ISSUE THREAD

**Issue by Xiaoxiong-Liu** [HumaticsLAB/GTM-Transformer#1]
I am very interested about the result in paper, and I want to compare the result in my dataset.
Can you release the code about other competitors model ?
Thanks.

**Comment by Xiaoxiong-Liu** [comment]
well, I find it, https://github.com/HumaticsLAB/AttentionBasedMultiModalRNN

**Comment by geriskenderi** [comment]
Thank you for your interest in our work, please remember to cite us if you use the code for GTM or the Attention-based multimodal RNNs
