### ISSUE TITLE
Dataset Question

### ISSUE THREAD

**Issue by Stefano-Salvatori** [HumaticsLAB/GTM-Transformer#3]
Thank you far sharing your dataset and solution.

I have a few question on the VISUELLE dataset: what is the '_extra_' column in the dataset? will you release an extended version of the dataset (i'm thinking about textual descriptions, products' title, prices...) ?

**Comment by geriskenderi** [comment]
Hi Stefano,

Thanks a lot for taking the time to check out our work. The "extra" column represents an attribute that is automatically extracted from the product images using an attribute extractor. We gave more details regarding this in our paper:

> "To explore the generalization of the model to additional types of visual attributes, we consider the tags from Fashion IQ [12]: they represent a widely known approach to describe fashion items for automated retrieval purposes. We apply the attribute extraction code directly to our data, focusing on the “shape” attribute, which describes fine-grained aspects of the structure of the product (v-neck, hem, . . . )."

As for your second question, we will update the repository with information regarding possible new releases. If you are interested, I will contact you directly in the eventuality of a new release. Thanks again!

**Comment by Stefano-Salvatori** [comment]
Ok got it. The gtrends file however does not have columns associated to these 'extra' attributes (except for sleeveless and long sleeves which are also in the category section). Am i missing something?

Yes i'm interested in new releases of the dataset, thank you!

**Comment by geriskenderi** [comment]
The reason for that was simply that it was an attribute that is "external" to the dataset. Basically, the test done with the "extra" attribute was to demonstrate the ability of the model to work with automatically extracted attributes. Given the images of the products, one can extract any number of attributes and then download the respective trends. The idea is that you are free to also use externally extracted attributes and rely on their google trends, but _these are not "native" to Visuelle_. If you wish or need to have them, I can send you personally a file containing also the trends for the extracted attributes (in similar fashion to the gtrends file in the dataset). Thanks again for your questions.

**Comment by Stefano-Salvatori** [comment]
Yes, I would appreciate if you could send me those files (as long as this doesn't take too much work).

Thank you for your time!
