### ISSUE TITLE
Parallelization during training

### ISSUE THREAD

**Issue by fmartinmonier** [HumaticsLAB/GTM-Transformer#6]
Hi! 
I've been playing around with the GTM network architecture and am struggling to parallelize training. My machine has 2 GPUs so it would be nice to speed up things a bit. I set the pl.Trainer to: 
`trainer = pl.Trainer(
        accelerator = "gpu",
        devices = 2,
        strategy = "ddp",
        max_epochs = args.epochs, 
        check_val_every_n_epoch = 5,
        callbacks = [checkpoint_callback],
        min_epochs = 1
    )`

but I'm getting the following error: 
`File "/*******************/multimodal-visuelle/models/GTM_saiso.py", line 153, in forward
    word_embeddings = self.dropout(self.fc(word_embeddings))
  File "/*******************/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/*******************/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/*******************/lib/python3.8/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_addmm)`

My question is not really regarding this bug but rather:
Have you trained the model on a single GPU or have you parallelized training? If yes, what did you modify in the code to make it work?

Thanks a lot for your time!

**Comment by geriskenderi** [comment]
Hi there,

Thanks for trying out the code. We've never tried training on multiple GPUs since the model always fit on one of ours, so we saw no real reason to do so. 

Let us know if you find a solution so that we can maybe add multi-gpu support.

Thanks again, best,
Geri

**Comment by fmartinmonier** [comment]
Hi Geri, 

Thanks for your answer. I'll work on it and do a pull request if I manage to make it work then. 

Best,
François
