### ISSUE TITLE
Error on running forward function in TextEmbedder and GTrendEmbedder

### ISSUE THREAD

**Issue by baghishani** [HumaticsLAB/GTM-Transformer#8]
Dear @joppichristian and @geriskenderi,

I get the error "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!" when running the model.

Upon deactivating TextEmbedder and GTrendEmbedder, the entire run succeeds, regarding updating validation_epoch_end to on_validation_epoch_end, but with these two parts, the error occurs.

On TextEmbedder, the error is caused on self.fc(word_embeddings). For both word_embeddings and the FC model, I used ".to('cuda:'+str(self.gpu_num))", but it didn't work.

torch:  2.0.1+cu117
pytorch_lightning:  2.0.3
With two GPU, NVIDIA V100

**Comment by joppichristian** [comment]
Hi @baghishani,
try installing version 1.9 (or versions less than 2.0) of torch. 

Christian

**Comment by baghishani** [comment]
Thanks, @joppichristian.
It worked. I also had to consider the compatible version of pytorch_lightning, in case it happens to someone else :)
